!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/js/script.js")}({"./src/js/components/burger.js":
/*!*************************************!*\
  !*** ./src/js/components/burger.js ***!
  \*************************************/
/*! exports provided: burger */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "burger", function() { return burger; });\nvar burger = function burger(burgerSelector, navSelector) {\n  var burger = document.querySelector(burgerSelector),\n      body = document.body,\n      nav = document.querySelector(navSelector);\n  burger.addEventListener("click", function (e) {\n    if (e.currentTarget) {\n      burger.classList.toggle("".concat(burgerSelector.substring(1, burgerSelector.length), "--active"));\n      nav.classList.toggle("".concat(navSelector.substring(1, navSelector.length), "--active"));\n      body.classList.toggle("lock");\n    }\n  });\n};\n\n//# sourceURL=webpack:///./src/js/components/burger.js?')},"./src/js/components/tabs.js":
/*!***********************************!*\
  !*** ./src/js/components/tabs.js ***!
  \***********************************/
/*! exports provided: tabs */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "tabs", function() { return tabs; });\nvar tabs = function tabs(tabsParentSelector, tabsSelector, tabsContentSelector, activeClass) {\n  var tabsParent = document.querySelector(tabsParentSelector),\n      tabs = tabsParent.querySelectorAll(tabsSelector),\n      tabsContent = document.querySelectorAll(tabsContentSelector);\n\n  function hideTabContent() {\n    tabs.forEach(function (item, i) {\n      item.classList.remove(activeClass.substring(1));\n    });\n    tabsContent.forEach(function (item) {\n      item.classList.add("hide");\n    });\n  }\n\n  function showTabContent() {\n    var i = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;\n    tabs[i].classList.add(activeClass.substring(1));\n    tabsContent[i].classList.remove("hide");\n  }\n\n  hideTabContent();\n  showTabContent();\n  tabsParent.addEventListener(\'click\', function (e) {\n    if (e.target && e.target.classList.contains(tabsSelector.substring(1))) {\n      tabs.forEach(function (item, i) {\n        if (e.target === item) {\n          hideTabContent();\n          showTabContent(i);\n        }\n      });\n    }\n  });\n};\n\n//# sourceURL=webpack:///./src/js/components/tabs.js?')},"./src/js/script.js":
/*!**************************!*\
  !*** ./src/js/script.js ***!
  \**************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_burger__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./components/burger */ "./src/js/components/burger.js");\n/* harmony import */ var _components_tabs__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./components/tabs */ "./src/js/components/tabs.js");\n\n\n\n\nwindow.addEventListener(\'DOMContentLoaded\', function () {\n  Object(_components_burger__WEBPACK_IMPORTED_MODULE_0__["burger"])(".header__burger", ".header__nav");\n  Object(_components_tabs__WEBPACK_IMPORTED_MODULE_1__["tabs"])(".about-main__tabs-head", ".about-main__tabs-head-item", ".about-main__tabs-content-item", ".about-main__tabs-head-item--active");\n});\n\n//# sourceURL=webpack:///./src/js/script.js?')}});
//# sourceMappingURL=script.js.map
